[package]
name = "callable_oracles"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
zk_ee = { path = "../zk_ee", default-features = false }
ruint = { workspace = true, default-features = false }
crypto = { workspace = true }
oracle_provider = { path = "../oracle_provider" }
basic_system = { path = "../basic_system", default-features = false }
basic_bootloader = { path = "../basic_bootloader", default-features = false }
serde = { workspace = true, default-features = false, features = ["derive"] }
airbender-codec = { workspace = true }
wincode = { workspace = true }

c-kzg = "2.1.5"

[features]
default = ["evaluate"]
evaluate = []
testing = []
