[package]
name = "proof_running_system"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zk_ee = { path = "../zk_ee", default-features = false }
evm_interpreter = { path = "../evm_interpreter", default-features = false }
basic_system = { path = "../basic_system", default-features = false }
system_hooks = { path = "../system_hooks", default-features = false }
basic_bootloader = { path = "../basic_bootloader", default-features = false }
ruint = { workspace = true, default-features = false }
crypto = { workspace = true }
u256 = { path = "../supporting_crates/u256", default-features = false }
cfg-if = { workspace = true }
talc = { version = "4.4.3", default-features = false, features = ["allocator", "nightly_api"]}
# talc = { path = "../../talc", default-features = false, features = ["allocator", "nightly_api"]}

[dev-dependencies]
hex = { workspace = true }
fastrand = "2.0.2"

[features]
testing = ["zk_ee/testing", "evm_interpreter/testing", "basic_system/testing", "basic_bootloader/testing"]
default = ["testing"]
proving = ["crypto/proving", "basic_system/proving", "delegation", "zk_ee/proving_env", "basic_bootloader/proving_env"]
delegation = ["u256/delegation", "zk_ee/delegation", "evm_interpreter/delegation", "basic_system/delegation", "system_hooks/delegation", "basic_bootloader/delegation"]
fri_precompile = ["basic_bootloader/fri_precompile", "system_hooks/fri_precompile"]
