[package]
name = "zksync_os"
version = "0.1.0"
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/zksync-os/"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync", "zk", "risc-v"]
categories = ["cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
airbender = { package = "airbender-sdk", git = "https://github.com/matter-labs/airbender-platform", rev = "7b7bd958b3abae3ba8c77e546098008b8c287b1a", default-features = false, features = ["allocator-custom"] }
proof_running_system = { path = "../proof_running_system", default-features = false }
crypto = { git = "https://github.com/matter-labs/airbender-platform", rev = "7b7bd958b3abae3ba8c77e546098008b8c287b1a", package = "airbender-crypto", default-features = false, optional = true }

[profile.dev]
opt-level = 0
lto = false
codegen-units = 1
panic = "abort"
debug = true

[profile.dev.overrides."*"]
opt-level = 0
lto = false
codegen-units = 1
panic = "abort"
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = false

[profile.release.overrides."*"]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
debug = false

[features]
scalloc = ["proof_running_system/scalloc"]
print_debug_info = ["proof_running_system/error_origins", "proof_running_system/global-alloc"]
proving = ["crypto/proving", "proof_running_system/proving"]
benchmarking = ["proof_running_system/benchmarking"]
production = ["proof_running_system/production"]
for_tests = ["proof_running_system/for_tests"]
fri_precompile = ["proof_running_system/fri_precompile"]
eth_runner = ["proof_running_system/eth_runner"]
eth_stf = ["proof_running_system/eth_stf"]
evm_tester = ["proof_running_system/evm_tester"]
multiblock-batch = ["proof_running_system/multiblock-batch"]
state-diffs-pi = ["proof_running_system/state-diffs-pi"]
# Selects the BPO2 blob-count schedule; default is base-Osaka.
fusaka-bpo-2 = ["proof_running_system/fusaka-bpo-2"]


# [patch."https://github.com/matter-labs/zksync-airbender"]
# blake2s_u32 = {git = "ssh://git@github.com/matter-labs/zksync-airbender.git", branch = "av_bigint_precompile" }
