use basic_system::system_implementation::ethereum_storage_model::ETHEREUM_QUERIES_SUBSPACE_MASK;
use zk_ee::oracle::query_ids::GENERIC_SUBSPACE_MASK;

pub const ETHEREUM_WITHDRAWALS_BUFFER_LEN_QUERY_ID: u32 =
    GENERIC_SUBSPACE_MASK | ETHEREUM_QUERIES_SUBSPACE_MASK | 1;
pub const ETHEREUM_WITHDRAWALS_BUFFER_DATA_QUERY_ID: u32 =
    GENERIC_SUBSPACE_MASK | ETHEREUM_QUERIES_SUBSPACE_MASK | 2;

pub const ETHEREUM_TARGET_HEADER_BUFFER_LEN_QUERY_ID: u32 =
    GENERIC_SUBSPACE_MASK | ETHEREUM_QUERIES_SUBSPACE_MASK | 3;
pub const ETHEREUM_TARGET_HEADER_BUFFER_DATA_QUERY_ID: u32 =
    GENERIC_SUBSPACE_MASK | ETHEREUM_QUERIES_SUBSPACE_MASK | 4;

pub const ETHEREUM_HISTORICAL_HEADER_BUFFER_LEN_QUERY_ID: u32 =
    GENERIC_SUBSPACE_MASK | ETHEREUM_QUERIES_SUBSPACE_MASK | 5;
pub const ETHEREUM_HISTORICAL_HEADER_BUFFER_DATA_QUERY_ID: u32 =
    GENERIC_SUBSPACE_MASK | ETHEREUM_QUERIES_SUBSPACE_MASK | 6;
