#!/usr/bin/env python3
"""
Overview log directories from parallel eth_runner processes.

Shows current status, progress, and metrics for running or completed eth-runner processes.

NOTE: This script was generated by AI. This script currently uses regex parsing of log files,
which is inconvenient and unmanageable. The plan is to move statistics collection to Rust code,
eliminating the need for log parsing. This script will then be simplified to read and display statistics.
"""

import re
import sys
import os
import argparse
import json
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple, Set, NamedTuple
from collections import defaultdict
from dataclasses import dataclass, field

# Compile regex patterns once at module level for performance
BLOCK_PATTERN = re.compile(r'Running block:\s*(\d+)')
ALL_GOOD_PATTERN = re.compile(r'All good!')
BLOCKS_PROCESSED_PATTERN = re.compile(r'Blocks actually processed:\s*(\d+)')
TOTAL_TIME_PATTERN = re.compile(r'\s+Total:\s+([\d.]+)ms')
BLOCKS_PER_SECOND_PATTERN = re.compile(r'Blocks per second:\s*([\d.]+)')
BLOCK_RANGE_PATTERN = re.compile(r'Blocks:\s*(\d+)\s+to\s+(\d+)')
LOG_LINE_PATTERN = re.compile(r'\[([^\]]+)\s+(ERROR|WARN|FATAL|INFO|DEBUG)\s+([^\]]+)\]\s*(.*)')
CARGO_WARNING_PATTERN = re.compile(r'^(warning:|^\s+\d+\s+\|\s+warning|^\s+= note:)', re.IGNORECASE)
CARGO_FAILED_PATTERN = re.compile(r'^\s+Finished|^\s+Compiling|^\s+Running `', re.IGNORECASE)
SKIP_ALREADY_SUCCEEDED_PATTERN = re.compile(r'Skipping block (\d+), already succeeded')
SKIP_UNSUPPORTED_PRECOMPILE_PATTERN = re.compile(r'Skipping block (\d+), as it calls to an unsupported precompile')
SKIP_FAILED_FETCH_PATTERN = re.compile(r'Failed to fetch traces for block (\d+)')
ERROR_PATTERN = re.compile(r'Block (\d+) failed with error')
BALANCE_ZERO_ADDRESS_PATTERN = re.compile(r'Balance for 0000000000000000000000000000000000000000')
GAS_MISMATCH_PATTERN = re.compile(r'has a gas mismatch: ZKsync OS used')
REFERENCE_WRITE_ERROR_PATTERN = re.compile(r'Reference must have write for account')

# Configuration constants
RECENT_ACTIVITY_LINES = 5  # Number of recent log lines to show per process when --show-activity is used


@dataclass
class LogData:
    """Data extracted from a single log file in a single pass."""
    blocks_processed: Optional[int] = None
    total_time_ms: Optional[float] = None
    blocks_per_second: Optional[float] = None
    blocks_started: Set[int] = field(default_factory=set)
    blocks_with_all_good: Set[int] = field(default_factory=set)
    last_block: Optional[int] = None
    block_range: Optional[Tuple[int, int]] = None
    error_count: int = 0
    errors: List[Dict[str, str]] = field(default_factory=list)
    skip_reasons: Dict[str, List[int]] = field(default_factory=lambda: defaultdict(list))
    error_patterns: Dict[str, int] = field(default_factory=lambda: {
        'balance_zero_address': 0,
        'gas_mismatch': 0,
        'reference_write_error': 0,
        'unknown': 0,  # Errors that don't match any known pattern
    })
    recent_lines: List[str] = field(default_factory=list)


def parse_log_file_single_pass(log_file: Path, include_recent_lines: bool = False) -> LogData:
    """Parse log file in a single pass, extracting all needed data."""
    data = LogData()
    current_block = None
    all_lines = []
    
    try:
        with open(log_file, 'r', errors='ignore') as f:
            for line_num, line in enumerate(f, 1):
                all_lines.append(line)
                
                # Skip cargo warnings early
                if CARGO_WARNING_PATTERN.match(line.strip()):
                    continue
                if CARGO_FAILED_PATTERN.match(line.strip()):
                    continue
                
                # Extract block range (usually near the start)
                if data.block_range is None:
                    match = BLOCK_RANGE_PATTERN.search(line)
                    if match:
                        data.block_range = (int(match.group(1)), int(match.group(2)))
                
                # Track running blocks
                match = BLOCK_PATTERN.search(line)
                if match:
                    current_block = int(match.group(1))
                    data.blocks_started.add(current_block)
                    data.last_block = current_block
                
                # Track "All good!" blocks
                if ALL_GOOD_PATTERN.search(line) and current_block is not None:
                    data.blocks_with_all_good.add(current_block)
                
                # Extract statistics (usually near the end)
                match = BLOCKS_PROCESSED_PATTERN.search(line)
                if match:
                    data.blocks_processed = int(match.group(1))
                
                match = TOTAL_TIME_PATTERN.search(line)
                if match:
                    data.total_time_ms = float(match.group(1))
                
                match = BLOCKS_PER_SECOND_PATTERN.search(line)
                if match:
                    data.blocks_per_second = float(match.group(1))
                
                # Extract errors
                log_match = LOG_LINE_PATTERN.search(line)
                is_error_line = False
                if log_match:
                    timestamp = log_match.group(1)
                    level = log_match.group(2)
                    module = log_match.group(3)
                    message = log_match.group(4)
                    
                    if level == 'ERROR' or (level == 'WARN' and ('failed' in message.lower() or 'panic' in message.lower())):
                        is_error_line = True
                        data.error_count += 1
                        data.errors.append({
                            'line': line_num,
                            'timestamp': timestamp,
                            'level': level,
                            'module': module,
                            'message': message.strip(),
                            'full_line': line.strip()
                        })
                
                # Track skip reasons
                match = SKIP_ALREADY_SUCCEEDED_PATTERN.search(line)
                if match:
                    data.skip_reasons['already_succeeded'].append(int(match.group(1)))
                
                match = SKIP_UNSUPPORTED_PRECOMPILE_PATTERN.search(line)
                if match:
                    data.skip_reasons['unsupported_precompile'].append(int(match.group(1)))
                
                match = SKIP_FAILED_FETCH_PATTERN.search(line)
                if match:
                    data.skip_reasons['failed_to_fetch'].append(int(match.group(1)))
                
                match = ERROR_PATTERN.search(line)
                if match:
                    data.skip_reasons['error'].append(int(match.group(1)))
                
                # Count error patterns (only for error lines, check in order, first match wins)
                if is_error_line:
                    if BALANCE_ZERO_ADDRESS_PATTERN.search(line):
                        data.error_patterns['balance_zero_address'] += 1
                    elif GAS_MISMATCH_PATTERN.search(line):
                        data.error_patterns['gas_mismatch'] += 1
                    elif REFERENCE_WRITE_ERROR_PATTERN.search(line):
                        data.error_patterns['reference_write_error'] += 1
        
        # Calculate unknown errors: total error count minus sum of known patterns
        known_patterns_sum = sum(data.error_patterns.values()) - data.error_patterns['unknown']
        data.error_patterns['unknown'] = max(0, len(data.errors) - known_patterns_sum)
        
        # Store recent lines if requested
        if include_recent_lines and all_lines:
            data.recent_lines = all_lines[-RECENT_ACTIVITY_LINES:] if len(all_lines) > RECENT_ACTIVITY_LINES else all_lines
            
    except Exception as e:
        # Silently handle errors - return partial data
        pass
    
    return data


def format_time_ms(ms: float) -> str:
    """Format milliseconds into human-readable time (days, hours, minutes, seconds)."""
    total_seconds = int(ms / 1000)
    days = total_seconds // 86400
    hours = (total_seconds % 86400) // 3600
    minutes = (total_seconds % 3600) // 60
    seconds = total_seconds % 60
    
    parts = []
    if days > 0:
        parts.append(f"{days}d")
    if hours > 0:
        parts.append(f"{hours}h")
    if minutes > 0:
        parts.append(f"{minutes}m")
    if seconds > 0 or not parts:
        parts.append(f"{seconds}s")
    
    return " ".join(parts)


def calculate_elapsed_time(metadata_file: Path) -> Optional[str]:
    """Calculate elapsed time since start from metadata file."""
    if not metadata_file.exists():
        return None
    
    try:
        with open(metadata_file, 'r') as f:
            for line in f:
                if line.startswith('Started:'):
                    start_str = line.replace('Started:', '').strip()
                    # Parse format: "2024-01-01 12:00:00 UTC"
                    try:
                        start_time = datetime.strptime(start_str, '%Y-%m-%d %H:%M:%S UTC').replace(tzinfo=timezone.utc)
                        now = datetime.now(timezone.utc)
                        elapsed = now - start_time
                        
                        hours = elapsed.seconds // 3600
                        minutes = (elapsed.seconds % 3600) // 60
                        seconds = elapsed.seconds % 60
                        
                        if elapsed.days > 0:
                            return f"{elapsed.days}d {hours}h {minutes}m {seconds}s"
                        elif hours > 0:
                            return f"{hours}h {minutes}m {seconds}s"
                        elif minutes > 0:
                            return f"{minutes}m {seconds}s"
                        else:
                            return f"{seconds}s"
                    except ValueError:
                        return None
    except Exception:
        return None
    
    return None


def check_process_running(pid: int) -> bool:
    """Check if a process with given PID is running."""
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False


def get_process_status(log_dir: Path, process_num: int) -> str:
    """Check if process is still running."""
    pids_file = log_dir / 'pids.txt'
    if not pids_file.exists():
        return "completed"
    
    try:
        with open(pids_file, 'r') as f:
            pids = [int(p.strip()) for p in f.read().split() if p.strip().isdigit()]
        
        if process_num <= len(pids):
            pid = pids[process_num - 1]
            if check_process_running(pid):
                return "running"
    except Exception:
        pass
    
    return "completed"


def save_errors_to_file(errors: Dict[str, List[Dict[str, str]]], output_file: Path) -> None:
    """Save collected errors to a JSON file."""
    output_data = {
        'timestamp': datetime.now(timezone.utc).isoformat(),
        'total_processes_with_errors': len(errors),
        'total_errors': sum(len(e) for e in errors.values()),
        'errors_by_process': errors
    }
    
    with open(output_file, 'w') as f:
        json.dump(output_data, f, indent=2)
    print(f"Errors saved to: {output_file}")


def parse_directory_name(dirname: str) -> Optional[Tuple[int, int, int]]:
    """Extract start_block, end_block, and num_procs from directory name."""
    # Support both patterns: logs_parallel_start_X_end_Y_procs_Z and sepolia_logs_parallel_start_X_end_Y_procs_Z
    patterns = [
        r'logs_parallel_start_(\d+)_end_(\d+)_procs_(\d+)',
        r'sepolia_logs_parallel_start_(\d+)_end_(\d+)_procs_(\d+)',
        r'.*_start_(\d+)_end_(\d+)_procs_(\d+)'
    ]
    
    for pattern in patterns:
        match = re.match(pattern, dirname)
        if match:
            return int(match.group(1)), int(match.group(2)), int(match.group(3))
    return None


def analyze_coverage(base_dir: Path, pattern: str = '*_start_*_end_*_procs_*') -> None:
    """Analyze coverage ranges from directory names to find gaps."""
    log_dirs = sorted(base_dir.glob(pattern))
    
    if not log_dirs:
        print(f"No directories matching pattern '{pattern}' found")
        return
    
    ranges = []
    for log_dir in log_dirs:
        result = parse_directory_name(log_dir.name)
        if result:
            start, end, num_procs = result
            ranges.append((start, end, num_procs, log_dir.name))
    
    if not ranges:
        print("No valid log directories found")
        return
    
    ranges.sort(key=lambda x: x[0])
    
    print("=== Coverage Analysis ===")
    print()
    print("Coverage ranges:")
    print("-" * 50)
    
    # Calculate unique blocks covered (using set to handle overlaps)
    unique_blocks = set()
    prev_end = None
    first_start = None
    gaps = 0
    gap_list = []
    
    for start, end, num_procs, dirname in ranges:
        # Add all blocks in this range to the set (handles overlaps automatically)
        unique_blocks.update(range(start, end + 1))
        
        if prev_end is None:
            first_start = start
            print(f"[{start} - {end}] ({end - start + 1} blocks, {num_procs} processes) - {dirname}")
        else:
            gap = start - prev_end - 1
            if gap > 0:
                print(f"[{start} - {end}] ({end - start + 1} blocks, {num_procs} processes, GAP: {gap} blocks) - {dirname}")
                gaps += 1
                gap_list.append((prev_end + 1, start - 1))
            elif start <= prev_end:
                # Overlap detected
                overlap = prev_end - start + 1
                print(f"[{start} - {end}] ({end - start + 1} blocks, {num_procs} processes, OVERLAP: {overlap} blocks with previous) - {dirname}")
            else:
                print(f"[{start} - {end}] ({end - start + 1} blocks, {num_procs} processes) - {dirname}")
        
        prev_end = max(prev_end, end) if prev_end is not None else end
    
    if first_start is not None and prev_end is not None:
        overall_range = prev_end - first_start + 1
        total_blocks_covered = len(unique_blocks)
        coverage_pct = (total_blocks_covered / overall_range) * 100 if overall_range > 0 else 0
        
        print()
        print("Summary:")
        print("-" * 50)
        print(f"First block: {first_start}")
        print(f"Last block: {prev_end}")
        print(f"Overall range: {overall_range} blocks")
        print(f"Total blocks covered (unique): {total_blocks_covered}")
        print(f"Coverage: {coverage_pct:.2f}%")
        print(f"Gaps found: {gaps}")
        
        if gaps > 0:
            print()
            print("Missing ranges:")
            for gap_start, gap_end in gap_list:
                print(f"  [{gap_start} - {gap_end}] ({gap_end - gap_start + 1} blocks)")
            print()
            print("⚠️  Coverage has gaps!")
        else:
            print()
            print("No gaps found - complete coverage!")
    print()


def analyze_block_coverage(log_path: Path, log_files: List[Path], log_data_by_process: Dict[int, LogData]) -> None:
    """Analyze which blocks were successfully processed and which are missing."""
    # Try to extract block range from metadata or directory name
    metadata_file = log_path / 'metadata.txt'
    start_block = None
    end_block = None
    num_procs = None
    
    if metadata_file.exists():
        with open(metadata_file, 'r') as f:
            for line in f:
                if line.startswith('Start Block:'):
                    start_block = int(line.split(':')[1].strip())
                elif line.startswith('End Block:'):
                    end_block = int(line.split(':')[1].strip())
                elif line.startswith('Number of Processes:'):
                    num_procs = int(line.split(':')[1].strip())
    
    if start_block is None or end_block is None:
        # Try to extract from directory name
        result = parse_directory_name(log_path.name)
        if result:
            start_block, end_block, num_procs = result
    
    if start_block is None or end_block is None:
        print("Could not determine block range for detailed analysis")
        return
    
    expected_blocks = set(range(start_block, end_block + 1))
    all_blocks_with_all_good = set()
    all_blocks_started = set()
    total_error_patterns = defaultdict(int)
    all_skip_reasons = defaultdict(set)
    
    print("=== Detailed Block Analysis ===")
    print()
    print(f"Expected block range: {start_block} - {end_block} ({len(expected_blocks)} blocks)")
    print()
    
    for log_file in log_files:
        match = re.search(r'process_(\d+)', log_file.stem)
        if not match:
            continue
        process_num = int(match.group(1))
        data = log_data_by_process.get(process_num)
        if not data:
            continue
        
        blocks_good = data.blocks_with_all_good
        blocks_started = data.blocks_started
        skip_reasons = data.skip_reasons
        error_patterns = data.error_patterns
        
        all_blocks_with_all_good.update(blocks_good)
        all_blocks_started.update(blocks_started)
        
        for key, count in error_patterns.items():
            total_error_patterns[key] += count
        
        for reason, blocks in skip_reasons.items():
            all_skip_reasons[reason].update(blocks)
        
        # Calculate process-specific range
        total_blocks = len(expected_blocks)
        blocks_per_process = total_blocks // (num_procs or len(log_files))
        remainder = total_blocks % (num_procs or len(log_files))
        
        blocks_before = 0
        for i in range(1, process_num):
            if i <= remainder:
                blocks_before += blocks_per_process + 1
            else:
                blocks_before += blocks_per_process
        
        if process_num <= remainder:
            proc_blocks_count = blocks_per_process + 1
        else:
            proc_blocks_count = blocks_per_process
        
        proc_start = start_block + blocks_before
        proc_end = proc_start + proc_blocks_count - 1
        proc_expected = set(range(proc_start, proc_end + 1))
        
        proc_missing = proc_expected - blocks_good - blocks_started
        started_but_failed = blocks_started - blocks_good
        
        print(f"Process {process_num} (blocks {proc_start}-{proc_end}):")
        print(f"  Blocks with 'All good!': {len(blocks_good)}")
        print(f"  Blocks started: {len(blocks_started)}")
        if proc_missing:
            print(f"  Missing blocks: {len(proc_missing)}")
            if len(proc_missing) <= 10:
                print(f"    {sorted(proc_missing)}")
            else:
                missing_sorted = sorted(proc_missing)
                print(f"    {missing_sorted[:10]} ... ({len(proc_missing)} total)")
        if started_but_failed:
            print(f"  Blocks started but failed: {len(started_but_failed)}")
            if len(started_but_failed) <= 10:
                print(f"    {sorted(started_but_failed)}")
        if skip_reasons:
            print(f"  Skip reasons:")
            for reason, blocks in skip_reasons.items():
                if blocks:
                    print(f"    {reason}: {len(blocks)} blocks")
        if any(error_patterns.values()):
            print(f"  Error patterns:")
            for key, count in error_patterns.items():
                if count > 0:
                    print(f"    {key}: {count}")
        print()
    
    # Overall summary
    missing_blocks = expected_blocks - all_blocks_with_all_good - all_blocks_started
    started_but_failed = all_blocks_started - all_blocks_with_all_good
    
    print("Overall Summary:")
    print(f"  Blocks with 'All good!': {len(all_blocks_with_all_good)}")
    print(f"  Blocks started: {len(all_blocks_started)}")
    print(f"  Missing blocks: {len(missing_blocks)}")
    if missing_blocks:
        missing_sorted = sorted(missing_blocks)
        if len(missing_sorted) <= 20:
            print(f"    {missing_sorted}")
        else:
            print(f"    {missing_sorted[:20]} ... ({len(missing_sorted)} total)")
    if started_but_failed:
        print(f"  Blocks started but failed: {len(started_but_failed)}")
        failed_sorted = sorted(started_but_failed)
        if len(failed_sorted) <= 20:
            print(f"    {failed_sorted}")
        else:
            print(f"    {failed_sorted[:20]} ... ({len(failed_sorted)} total)")
    if all_skip_reasons:
        print(f"  Skip reasons (across all processes):")
        for reason, blocks in all_skip_reasons.items():
            if blocks:
                print(f"    {reason}: {len(blocks)} blocks")
    if any(total_error_patterns.values()):
        print(f"  Error patterns (across all processes):")
        for key, count in total_error_patterns.items():
            if count > 0:
                print(f"    {key}: {count}")
    print()


def overview_log_directory(log_dir: str, show_activity: bool = False, 
                           show_coverage: bool = False, show_block_analysis: bool = False,
                           save_errors: Optional[str] = None) -> None:
    """Main overview function."""
    log_path = Path(log_dir)
    
    if not log_path.exists() or not log_path.is_dir():
        print(f"Error: Log directory '{log_dir}' does not exist", file=sys.stderr)
        sys.exit(1)
    
    print(f"=== ETH Runner Status: {log_dir} ===")
    print()
    
    # Check if processes are still running
    pids_file = log_path / 'pids.txt'
    if pids_file.exists():
        try:
            with open(pids_file, 'r') as f:
                pids = [int(p.strip()) for p in f.read().split() if p.strip().isdigit()]
            running = sum(1 for pid in pids if check_process_running(pid))
            print(f"Processes still running: {running} / {len(pids)}")
            print()
        except Exception:
            pass
    
    # Find all log files
    log_files = sorted(log_path.glob('process_*.log'), 
                      key=lambda p: int(re.search(r'(\d+)', p.stem).group(1)) 
                      if re.search(r'(\d+)', p.stem) else 0)
    
    if not log_files:
        print("No log files found in log directory")
        sys.exit(1)
    
    print(f"Found {len(log_files)} log files")
    print()
    
    # Summary for each process
    print("=== Per-Process Summary ===")
    total_blocks = 0
    total_bps = 0.0
    valid_processes = 0
    max_time_ms = 0.0  # For parallel processes, use max time, not sum
    process_times = []  # Track individual process times
    
    # Parse all log files in single pass (more efficient)
    log_data_by_process = {}
    for log_file in log_files:
        match = re.search(r'process_(\d+)', log_file.stem)
        if match:
            process_num = int(match.group(1))
            # Single pass parse - extracts all needed data at once
            log_data_by_process[process_num] = parse_log_file_single_pass(log_file, include_recent_lines=show_activity)
    
    for log_file in log_files:
        # Extract process number from filename
        match = re.search(r'process_(\d+)', log_file.stem)
        if not match:
            continue
        process_num = int(match.group(1))
        data = log_data_by_process.get(process_num)
        if not data:
            continue
        
        status = get_process_status(log_path, process_num)
        print(f"Process {process_num} ({status}):")
        
        # For running processes, show progress
        if status == "running" and data.blocks_processed is None:
            blocks_running = len(data.blocks_started)
            last_block = data.last_block
            block_range = data.block_range
            elapsed_time = calculate_elapsed_time(log_path / 'metadata.txt')
            
            if block_range:
                start_block, end_block = block_range
                total_blocks_range = end_block - start_block + 1
                if blocks_running > 0 and total_blocks_range > 0:
                    percentage = (blocks_running / total_blocks_range) * 100.0
                    print(f"  Blocks processed so far: {blocks_running} / {total_blocks_range} ({percentage:.1f}%)")
                    if last_block:
                        print(f"  Last block: {last_block}")
                    if elapsed_time:
                        print(f"  Time spent: {elapsed_time}")
                elif blocks_running > 0:
                    print(f"  Blocks processed so far: {blocks_running}")
                    if last_block:
                        print(f"  Last block: {last_block}")
                    if elapsed_time:
                        print(f"  Time spent: {elapsed_time}")
                else:
                    print("  No blocks processed yet (may still be initializing)")
                    if elapsed_time:
                        print(f"  Time spent: {elapsed_time}")
            elif blocks_running > 0:
                print(f"  Blocks processed so far: {blocks_running}")
                if last_block:
                    print(f"  Last block: {last_block}")
            else:
                print("  No blocks processed yet (may still be initializing)")
        elif data.blocks_processed and data.blocks_processed > 0:
            print(f"  Blocks processed: {data.blocks_processed}")
            if data.total_time_ms:
                formatted_time = format_time_ms(data.total_time_ms)
                print(f"  Total time: {formatted_time}")
                process_times.append(data.total_time_ms)
                max_time_ms = max(max_time_ms, data.total_time_ms)
            if data.blocks_per_second:
                print(f"  Blocks per second: {data.blocks_per_second:.2f}")
                total_bps += data.blocks_per_second
            total_blocks += data.blocks_processed
            valid_processes += 1
        else:
            print("  No blocks processed yet (may still be running)")
        
        print()
    
    # Overall summary
    if valid_processes > 0:
        print("=== Overall Summary ===")
        print(f"Total blocks processed: {total_blocks}")
        if max_time_ms > 0:
            formatted_total_time = format_time_ms(max_time_ms)
            print(f"Total time (wall-clock, max across processes): {formatted_total_time}")
            if len(process_times) > 1:
                min_time_ms = min(process_times)
                avg_time_ms = sum(process_times) / len(process_times)
                print(f"  Min process time: {format_time_ms(min_time_ms)}")
                print(f"  Max process time: {format_time_ms(max_time_ms)}")
                print(f"  Avg process time: {format_time_ms(avg_time_ms)}")
        if valid_processes > 0:
            avg_bps = total_bps / valid_processes if valid_processes > 0 else 0.0
            print(f"Average blocks per second: {avg_bps:.2f}")
        print()
    
    # Check for errors (using already parsed data)
    print("=== Error Check ===")
    error_count = 0
    processes_with_errors = []
    all_errors = {}
    
    for process_num, data in log_data_by_process.items():
        if data.error_count > 0:
            print(f"Process {process_num}: {data.error_count} error(s) found")
            processes_with_errors.append((process_num, data.error_count))
            error_count += data.error_count
            if data.errors:
                all_errors[str(process_num)] = data.errors
    
    if error_count == 0:
        print("No errors found in logs")
    else:
        print(f"Total errors found: {error_count}")
        if processes_with_errors:
            print(f"Processes with errors: {', '.join(f'{p}({e})' for p, e in processes_with_errors)}")
    print()
    
    # Save errors to file if requested
    if save_errors:
        output_path = Path(save_errors)
        save_errors_to_file(all_errors, output_path)
        print()
    
    # Show detailed block analysis if requested
    if show_block_analysis:
        analyze_block_coverage(log_path, log_files, log_data_by_process)
    
    # Show coverage analysis if requested
    if show_coverage:
        # Look in parent directory for multiple log directories
        base_dir = log_path.parent
        # Try current directory first, then parent
        if not list(base_dir.glob('*_start_*_end_*_procs_*')):
            base_dir = log_path
        analyze_coverage(base_dir)
    
    # Show recent log entries (optional, using already parsed data)
    if show_activity:
        print(f"=== Recent Activity (last {RECENT_ACTIVITY_LINES} lines per process) ===")
        for process_num in sorted(log_data_by_process.keys()):
            data = log_data_by_process[process_num]
            print(f"Process {process_num}:")
            for line in data.recent_lines[-RECENT_ACTIVITY_LINES:]:
                print(f"  {line.rstrip()}")
            print()


def main():
    # Check OS - only support Linux and macOS
    if sys.platform.startswith('win'):
        print("Error: This script only supports Linux and macOS. Windows is not supported.", file=sys.stderr)
        sys.exit(1)
    
    parser = argparse.ArgumentParser(
        description='Overview status of parallel eth-runner processes',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic overview
  %(prog)s logs_parallel_start_19299000_end_19300000_procs_20
  
  # Show recent activity (useful for monitoring running processes)
  %(prog)s logs_parallel_start_19299000_end_19300000_procs_20 --show-activity
  
  # Detailed block analysis (missing blocks, skip reasons, error patterns)
  %(prog)s logs_parallel_start_19299000_end_19300000_procs_20 --block-analysis
  
  # Save all errors to JSON file for later analysis
  %(prog)s logs_parallel_start_19299000_end_19300000_procs_20 --save-errors errors.json
  
  # Coverage analysis (finds gaps across multiple log directories)
  %(prog)s logs_parallel_start_19299000_end_19300000_procs_20 --coverage
  
  # Combine multiple features
  %(prog)s logs_parallel_start_19299000_end_19300000_procs_20 --block-analysis --save-errors errors.json

Features integrated from other scripts:
  - analyze_log_coverage.sh: Coverage gap detection (--coverage flag)
  - analyze_timing_breakdown.py: Detailed block analysis (--block-analysis flag)
  - Error collection: Automatic error extraction and JSON export (--save-errors flag)
        """
    )
    parser.add_argument(
        'log_dir',
        nargs='?',
        default='logs_parallel',
        help='Log directory to overview (default: logs_parallel)'
    )
    parser.add_argument(
        '--show-activity',
        action='store_true',
        help=f'Show recent activity (last {RECENT_ACTIVITY_LINES} lines per process)'
    )
    parser.add_argument(
        '--block-analysis',
        action='store_true',
        help='Show detailed block analysis (missing blocks, skip reasons, error patterns)'
    )
    parser.add_argument(
        '--coverage',
        action='store_true',
        help='Show coverage analysis (find gaps across multiple log directories)'
    )
    parser.add_argument(
        '--save-errors',
        metavar='FILE',
        help='Save all errors to JSON file'
    )
    
    args = parser.parse_args()
    overview_log_directory(
        args.log_dir, 
        args.show_activity,
        args.coverage,
        args.block_analysis,
        args.save_errors
    )


if __name__ == '__main__':
    main()
