//
// AUTOGENERATED BASED ON A SET OF JSON FILES, DO NOT EDIT MANUALLY
//
pub(crate) mod definitions;
pub(crate) mod domains;
use crate::error::domains::Compiler;
use crate::error::domains::Core;
use crate::error::domains::ExecutionEnvironment;
use crate::error::domains::Foundry;
use crate::error::domains::Hardhat;
use crate::error::domains::Os;
use crate::error::domains::ZksyncError;
use crate::identifier::Identifier;
use core::error::Error;
pub trait IError<ContainedType>: Error
where
    ContainedType: Clone,
{
    fn get_identifier(&self) -> Identifier;
    fn write_message<W: core::fmt::Write>(&self, writer: &mut W) -> core::fmt::Result;
    fn get_data(&self) -> ContainedType;
}
#[cfg(not(feature = "use_serde"))]
pub trait IUnifiedError<ContainedType>: IError<ContainedType>
where
    ContainedType: Clone,
{
}
#[cfg(feature = "use_serde")]
pub trait IUnifiedError<ContainedType>:
    serde::Serialize + for<'de> serde::Deserialize<'de> + IError<ContainedType>
where
    ContainedType: Clone,
{
}
pub trait ICustomError<U, C>
where
    U: IUnifiedError<C>,
    C: Clone,
{
    fn to_unified(&self) -> U;
}
pub trait CustomErrorMessageWriter {
    fn write_message<W: core::fmt::Write>(&self, writer: &mut W) -> core::fmt::Result;
}
#[cfg(feature = "std")]
pub trait CustomErrorMessage {
    fn get_message(&self) -> String;
}
#[cfg(feature = "std")]
impl<T> CustomErrorMessage for T
where
    T: CustomErrorMessageWriter,
{
    fn get_message(&self) -> String {
        let mut s = String::new();
        self.write_message(&mut s);
        s
    }
}
impl CustomErrorMessageWriter for ZksyncError {
    fn write_message<W: core::fmt::Write>(&self, writer: &mut W) -> core::fmt::Result {
        match self {
            ZksyncError::Compiler(Compiler::LLVM_EVM(error)) => error.write_message(writer),
            ZksyncError::Compiler(Compiler::LLVM_Era(error)) => error.write_message(writer),
            ZksyncError::Compiler(Compiler::Solc(error)) => error.write_message(writer),
            ZksyncError::Compiler(Compiler::SolcFork(error)) => error.write_message(writer),
            ZksyncError::Compiler(Compiler::Zksolc(error)) => error.write_message(writer),
            ZksyncError::Compiler(Compiler::Zkvyper(error)) => error.write_message(writer),
            ZksyncError::Core(Core::API(error)) => error.write_message(writer),
            ZksyncError::Core(Core::EraVM(error)) => error.write_message(writer),
            ZksyncError::Core(Core::ExecutionPlatform(error)) => error.write_message(writer),
            ZksyncError::Core(Core::Sequencer(error)) => error.write_message(writer),
            ZksyncError::ExecutionEnvironment(ExecutionEnvironment::Common(error)) => {
                error.write_message(writer)
            }
            ZksyncError::ExecutionEnvironment(ExecutionEnvironment::EVM(error)) => {
                error.write_message(writer)
            }
            ZksyncError::ExecutionEnvironment(ExecutionEnvironment::Native(error)) => {
                error.write_message(writer)
            }
            ZksyncError::ExecutionEnvironment(ExecutionEnvironment::WASM(error)) => {
                error.write_message(writer)
            }
            ZksyncError::Foundry(Foundry::FoundryUpstream(error)) => error.write_message(writer),
            ZksyncError::Foundry(Foundry::FoundryZksync(error)) => error.write_message(writer),
            ZksyncError::Hardhat(Hardhat::HardhatUpstream(error)) => error.write_message(writer),
            ZksyncError::Hardhat(Hardhat::HardhatZksync(error)) => error.write_message(writer),
            ZksyncError::Os(Os::Storage(error)) => error.write_message(writer),
            ZksyncError::Os(Os::System(error)) => error.write_message(writer),
            ZksyncError::Os(Os::SystemEnvironment(error)) => error.write_message(writer),
        }
    }
}
#[cfg(feature = "std")]
pub trait NamedError {
    fn get_error_name(&self) -> &'static str;
}
impl IError<ZksyncError> for ZksyncError {
    fn get_identifier(&self) -> Identifier {
        Identifier {
            kind: self.get_kind(),
            code: self.get_code(),
        }
    }
    fn write_message<W: core::fmt::Write>(&self, writer: &mut W) -> core::fmt::Result {
        <Self as CustomErrorMessageWriter>::write_message(self, writer)
    }
    fn get_data(&self) -> ZksyncError {
        self.clone()
    }
}
