# This workflow just builds the fuzz targets without running them.
name: Daily Fuzz Build

on:
  schedule:
    - cron: '0 1 * * *'

permissions: read-all

jobs:
  build-fuzz-targets:
    name: Build fuzz targets
    runs-on: [matterlabs-ci-runner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          rustflags: ""

      - name: Setup
        run: |
          rustup set profile minimal
          rustup target add riscv32i-unknown-none-elf
          rustup target add wasm32-unknown-unknown
          cargo install cargo-binutils
          rustup component add llvm-tools-preview
          rustup component add rust-src

      - name: Compile for RISC-V
        working-directory: ./zksync_os
        run: ./dump_bin.sh

      - name: Build wasm contracts
        run: |
          for dir in ./tests/contracts_wasm/*; do
            if [ -d "$dir" ]; then
              echo "Building contract in $dir"
              (cd "$dir" && ./build.sh)
            fi
          done

      - name: Compile for forward running
        run: cargo build --release

      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz

      - name: Build fuzz tests
        run: |
          cd tests/fuzzer
          cargo fuzz build -D

      - name: Run regression tests
        run: |
          cd tests/fuzzer
          ./fuzz.sh regression

      - name: Run smoke fuzz tests
        run: |
          cd tests/fuzzer
          ./fuzz.sh smoke